version: "2"
services:
  web:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    links:
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGODBURI: "${MONGODBURI}"
      BROKER_URI: rabbitmq
      PREFETCH_COUNT: 3
  mongo:
    container_name: payment_mongo
    image: mongo
    hostname: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: 'rabbitmq'
    ports:
        - "5673:5672"
        - "15673:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/mnesia
    networks:
        - rabbitmq_nodejs 
networks:
  rabbitmq_nodejs:
    driver: bridge 
